### ISSUE TITLE
adb shell sendevent: /dev/input/event4: Permission denied

### ISSUE THREAD

**Issue by kiroo92** [zhangtianxiang/sky_music_player#1]
小米9.miui12，安卓10，已经root了，是系统限制吗，sendevent命令Permission denied

**Comment by zhangtianxiang** [comment]
> 小米9.miui12，安卓10，已经root了，是系统限制吗，sendevent命令Permission denied

我手机是米10 MIUI12，但是没有root所以没有测试。平板是华为matepad pro，华为没法root所以也没有测试。

你可以检查一下两个问题：
1. 你的屏幕输入设备是不是 event4
2. 开发者选项中应该有一个“USB调试（安全设置）”，打开这个MIUI才会允许模拟点击

**Comment by zhangtianxiang** [comment]
另外我已经找到了不用直接使用adb的更方便和强大的方法，可以高频同时点击多键，在此之上可以做监听键盘输入、直接读取MIDI文件、本地播放音符、钢琴可视化或光遇15键可视化，我也已经做了一个类似于音游缩圈的可视化，到时候发到bili。这个repo属于早期尝试，有点想弃了QAQ

**Comment by kiroo92** [comment]
果然是大佬，太强了，期待哈哈

**Comment by zhangtianxiang** [comment]
old issue
