### ISSUE TITLE
可以根据idb开发一个ios的吗？

### ISSUE THREAD

**Issue by jessemoe** [zhangtianxiang/sky_music_player#2]
看了一下idb（ios debug bridge)的api跟adb差不多，大佬是否可以写一个ios的脚本

**Comment by zhangtianxiang** [comment]
> 看了一下idb（ios debug bridge)的api跟adb差不多，大佬是否可以写一个ios的脚本

我这里没有ios设备，没办法调试。这是一个早期的尝试，不太完美。现在没什么时间更新了。

**Comment by jessemoe** [comment]
> > 看了一下idb（ios debug bridge)的api跟adb差不多，大佬是否可以写一个ios的脚本
> 
> 我这里没有ios设备，没办法调试。这是一个早期的尝试，不太完美。现在没什么时间更新了。

好的，等我买了MacBook写好之后再给你提pr
